[CmdletBinding()]
param(
    [string]$OutputDirectory = (Join-Path $PSScriptRoot '..\artifacts\API_DEPLOY')
)

$ErrorActionPreference = 'Stop'

$projectRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$apiProject = Join-Path $projectRoot 'backend\src\CaneFactory.API\CaneFactory.API.csproj'

if ((Test-Path -LiteralPath $OutputDirectory) -and
    (Get-ChildItem -LiteralPath $OutputDirectory -Force | Select-Object -First 1)) {
    throw "Output directory is not empty: $OutputDirectory. Use a new empty directory."
}

dotnet publish $apiProject -c Release -o $OutputDirectory
if ($LASTEXITCODE -ne 0) { throw 'API publish failed.' }

$unsafeSettings = Join-Path $OutputDirectory 'appsettings.json'
if (Test-Path -LiteralPath $unsafeSettings) {
    throw 'Unsafe API package: source appsettings.json was included and could overwrite the server configuration.'
}

# IIS web.config often contains server-only environment variables. Keep the
# already configured server copy during an update instead of replacing it with
# the generic file generated by dotnet publish.
$generatedWebConfig = Join-Path $OutputDirectory 'web.config'
if (Test-Path -LiteralPath $generatedWebConfig) {
    Remove-Item -LiteralPath $generatedWebConfig -Force
}

Write-Host "API deployment package created: $OutputDirectory"
Write-Host 'appsettings.json and web.config were intentionally excluded.'
Write-Host 'Copy this update package over the existing IIS folder without deleting its server-only configuration files.'
